[project]
name = "desctop-clock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.16.0",
    "pyside6>=6.10.0",
]
